version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: foodhub_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: foodhub
    volumes:
      - mongodb_data:/data/db
    networks:
      - foodhub_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: foodhub_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password@mongodb:27017/foodhub?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      PORT: 5000
      # Add CORS origin for frontend
      CORS_ORIGIN: ${FRONTEND_URL:-http://localhost:3000}
    depends_on:
      - mongodb
    networks:
      - foodhub_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Pass backend URL as build argument
        VITE_API_URL: ${BACKEND_URL:-http://localhost:5000/api}
    container_name: foodhub_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - foodhub_network

volumes:
  mongodb_data:

networks:
  foodhub_network:
    driver: bridge